name: React app

on:
  push:
    branches: [ release/1.0 ]
  pull_request:
    branches: [ release/1.0 ]

jobs:
  push:
    runs-on: self-hosted
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: proscheduler/pro-scheduler:webapplication-v1.0
          file: /docker/Dockerfile
